### ISSUE TITLE
Question about pre-trained model and training iterations

### ISSUE THREAD

**Issue by Trainingzy** [W-zx-Y/SM-PPM#1]
Thanks for your great work!

As in your paper, you only train the model for 500 iterations. It seems ridiculous. Previous works train the model for thousands of iterations (AdaptSeg-150K (UDA with deeplabv2), Advent-150K (UDA with deeplabv2), ASM-100K (OSDA)). How can the model converge with only 500 iterations? 

Do you train the source only model first?  I also found you load a model in your scripts, what is it?

**Comment by W-zx-Y** [comment]
Thank you for your interest in our work.
Yes, 500 iteration-training is achieved by a source-only pre-trained model. Training from scratch requires more training iterations as shown in Figure 8.

**Comment by Trainingzy** [comment]
Thanks for the reply.

Can you release the source-only pre-trained model?

**Comment by W-zx-Y** [comment]
> Thanks for the reply.
> 
> Can you release the source-only pre-trained model?

The pre-trained models have been released in the readme file. Let me know whether they work.

**Comment by Trainingzy** [comment]
Cool!. Thanks
