### ISSUE TITLE
Dark Zurich Dataset

### ISSUE THREAD

**Issue by SnowdenLee** [W-zx-Y/SM-PPM#2]
Hello, 
thanks for the interesting work. I tried to run the experiment on day-to-night. However, I didn't find scripts for the Dark Zurich dataset. Could you please also upload the codes for it? Thanks a lot :)

**Comment by W-zx-Y** [comment]
Hi Snowden,

You can download the original codes of "day-to-night" experiments in [d2n_exp.zip](https://github.com/W-zx-Y/SM-PPM/files/8550310/d2n_exp.zip).
Please put them into the project. Currently, these codes are not very well refined and some paths may need to be changed to get it run correctly.  You can refer to the code for the GTA5-Cityscapes setting.

**Comment by SnowdenLee** [comment]
Hi, thanks a lot. I will give a try :)

**Comment by SnowdenLee** [comment]
Hi, 
sorry I have another question. I checked your code and saw you resized the images to 321x321. So all mIoU results in the paper are evaluted on 321x321 not the original resolution?
Thanks in advance!

**Comment by W-zx-Y** [comment]
Hi, 
This is the evaluation code [evaluate_night.zip](https://github.com/W-zx-Y/SM-PPM/files/8555634/evaluate_night.zip) for "day-to-night" experiments.  As shown in Line102, the real _crop_size_ is (1024, 512).

**Comment by SnowdenLee** [comment]
Hi, I have one more question. In the paper you mentioned you run day-to-night experiment with 4 images (one for each experiment) and 5 times. May I ask which 4 images did you use? Thanks a lot!

**Comment by W-zx-Y** [comment]
4 images from Dark Zurich Dataset shown below are used in our day-to-night experiments.
> train/night/GOPR0351/GOPR0351_frame_000002_rgb_anon.png
> train/night/GOPR0351/GOPR0351_frame_000003_rgb_anon.png
> train/night/GOPR0351/GOPR0351_frame_000004_rgb_anon.png
> train/night/GOPR0351/GOPR0351_frame_000005_rgb_anon.png
